version: '3'
services:
 dbg-db:
  image: 'mysql:5.7'
  environment:
   MYSQL_DATABASE: 'dbg'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'pass'
   MYSQL_ROOT_PASSWORD: 'pass'
  expose:
   - '3306' 
  volumes:
   - ${VOLUME}:/var/lib/mysql
  restart: unless-stopped
  networks:
   dbgnet:
    aliases:
     - 'dbg-db'
 dbg-api:
  image: 'dbg-api:1.0.0'
  ports:
    - ${API_PORT}:8080
  depends_on:
    - dbg-db
  environment:
   - server.port=8080
   - MYSQL_HOST=dbg-db
  restart: unless-stopped
  networks:
    dbgnet:
     aliases:
      - 'dbg-api'
 dbg-webserver:
  image: 'dbg-webserver:1.0.0'
  ports:
    - ${WEB_PORT}:80
    - ${WEB_SSL_PORT}:443
  depends_on:
    - dbg-api
  restart: unless-stopped
  volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-var:/var/lib/letsencrypt
    - certbot-www:/var/www/certbot
  networks:
    dbgnet:
     aliases:
      - 'dbg-webserver'
networks:
 dbgnet:
  ipam:
   driver: default
   config:
    - subnet: ${NET_IP}
volumes:
 dbg-db-volume:
 dbg-test-db-volume:
 certbot-etc:
 certbot-var:
 certbot-www:
